/* Copyright 2018-present The KotlinNLP Authors. All Rights Reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * L"* ", "icense, v. 2.0. If a copy of the MPL was not distributed with this
 * f"* ", "ile, You can obtain one at http://mozilla.org/MPL/2.0/.
 * ------------------------------------------------------------------*/

package com.kotlinnlp.geolocation.structures

/**
 * The ISO 639-1 language code.
 */
enum class LanguageISOCode(val annotation: String, val languageName: String) {
  AA("AA", "Afar"),
  AB("AB", "Abkhazian"),
  AE("AE", "Avestan"),
  AF("AF", "Afrikaans"),
  AK("AK", "Akan"),
  AM("AM", "Amharic"),
  AN("AN", "Aragonese"),
  AR("AR", "Arabic"),
  AS("AS", "Assamese"),
  AV("AV", "Avaric"),
  AY("AY", "Aymara"),
  AZ("AZ", "Azerbaijani"),
  BA("BA", "Bashkir"),
  BE("BE", "Belarusian"),
  BG("BG", "Bulgarian"),
  BH("BH", "Bihari languages"),
  BI("BI", "Bislama"),
  BM("BM", "Bambara"),
  BN("BN", "Bengali"),
  BO("BO", "Tibetan"),
  BR("BR", "Breton"),
  BS("BS", "Bosnian"),
  CA("CA", "Catalan"),
  CE("CE", "Chechen"),
  CH("CH", "Chamorro"),
  CO("CO", "Corsican"),
  CR("CR", "Cree"),
  CS("CS", "Czech"),
  CU("CU", "Old Church Slavonic"),
  CV("CV", "Chuvash"),
  CY("CY", "Welsh"),
  DA("DA", "Danish"),
  DE("DE", "German"),
  DV("DV", "Maldivian"),
  DZ("DZ", "Dzongkha"),
  EE("EE", "Ewe"),
  EL("EL", "Greek, Modern (1453)"),
  EN("EN", "English"),
  EO("EO", "Esperanto"),
  ES("ES", "Spanish"),
  ET("ET", "Estonian"),
  EU("EU", "Basque"),
  FA("FA", "Persian"),
  FF("FF", "Fulah"),
  FI("FI", "Finnish"),
  FJ("FJ", "Fijian"),
  FO("FO", "Faroese"),
  FR("FR", "French"),
  FY("FY", "Western Frisian"),
  GA("GA", "Irish"),
  GD("GD", "Gaelic"),
  GL("GL", "Galician"),
  GN("GN", "Guarani"),
  GU("GU", "Gujarati"),
  GV("GV", "Manx"),
  HA("HA", "Hausa"),
  HE("HE", "Hebrew"),
  HI("HI", "Hindi"),
  HO("HO", "Hiri Motu"),
  HR("HR", "Croatian"),
  HT("HT", "Haitian"),
  HU("HU", "Hungarian"),
  HY("HY", "Armenian"),
  HZ("HZ", "Herero"),
  IA("IA", "Interlingua (International Auxiliary Language Association"),
  ID("ID", "Indonesian"),
  IE("IE", "Interlingua"),
  IG("IG", "Igbo"),
  II("II", "Nuosu"),
  IK("IK", "Inupiaq"),
  IO("IO", "Ido"),
  IS("IS", "Icelandic"),
  IT("IT", "Italian"),
  IU("IU", "Inuktitut"),
  JA("JA", "Japanese"),
  JV("JV", "Javanese"),
  KA("KA", "Georgian"),
  KG("KG", "Kongo"),
  KI("KI", "Gikuyu"),
  KJ("KJ", "Kwanyama"),
  KK("KK", "Kazakh"),
  KL("KL", "Greenlandic"),
  KM("KM", "Central Khmer"),
  KN("KN", "Kannada"),
  KO("KO", "Korean"),
  KR("KR", "Kanuri"),
  KS("KS", "Kashmiri"),
  KU("KU", "Kurdish"),
  KV("KV", "Komi"),
  KW("KW", "Cornish"),
  KY("KY", "Kyrgyz"),
  LA("LA", "Latin"),
  LB("LB", "Luxembourgish"),
  LG("LG", "Ganda"),
  LI("LI", "Limburgan"),
  LN("LN", "Lingala"),
  LO("LO", "Lao"),
  LT("LT", "Lithuanian"),
  LU("LU", "Luba-Katanga"),
  LV("LV", "Latvian"),
  MG("MG", "Malagasy"),
  MH("MH", "Marshallese"),
  MI("MI", "Maori"),
  MK("MK", "Macedonian"),
  ML("ML", "Malayalam"),
  MN("MN", "Mongolian"),
  MR("MR", "Marathi"),
  MS("MS", "Malay"),
  MT("MT", "Maltese"),
  MY("MY", "Burmese"),
  NA("NA", "Nauru"),
  NB("NB", "Norwegian Bokmål"),
  ND("ND", "North Ndebele"),
  NE("NE", "Nepali"),
  NG("NG", "Ndonga"),
  NL("NL", "Dutch"),
  NN("NN", "Norwegian Nynorsk"),
  NO("NO", "Norwegian"),
  NR("NR", "South Ndebele"),
  NV("NV", "Navajo"),
  NY("NY", "Chewa"),
  OC("OC", "Occitan (post 1500)"),
  OJ("OJ", "Ojibwa"),
  OM("OM", "Oromo"),
  OR("OR", "Oriya"),
  OS("OS", "Ossetian"),
  PA("PA", "Panjabi"),
  PI("PI", "Pali"),
  PL("PL", "Polish"),
  PS("PS", "Pashto"),
  PT("PT", "Portuguese"),
  QU("QU", "Quechua"),
  RM("RM", "Romansh"),
  RN("RN", "Rundi"),
  RO("RO", "Romanian, Moldovan"),
  RU("RU", "Russian"),
  RW("RW", "Kinyarwanda"),
  SA("SA", "Sanskrit"),
  SC("SC", "Sardinian"),
  SD("SD", "Sindhi"),
  SE("SE", "Northern Sami"),
  SG("SG", "Sango"),
  SI("SI", "Sinhala"),
  SK("SK", "Slovak"),
  SL("SL", "Slovenian"),
  SM("SM", "Samoan"),
  SN("SN", "Shona"),
  SO("SO", "Somali"),
  SQ("SQ", "Albanian"),
  SR("SR", "Serbian"),
  SS("SS", "Swati"),
  ST("ST", "Sotho, Southern"),
  SU("SU", "Sundanese"),
  SV("SV", "Swedish"),
  SW("SW", "Swahili"),
  TA("TA", "Tamil"),
  TE("TE", "Telugu"),
  TG("TG", "Tajik"),
  TH("TH", "Thai"),
  TI("TI", "Tigrinya"),
  TK("TK", "Turkmen"),
  TL("TL", "Tagalog"),
  TN("TN", "Tswana"),
  TO("TO", "Tonga (Tonga Islands)"),
  TR("TR", "Turkish"),
  TS("TS", "Tsonga"),
  TT("TT", "Tatar"),
  TW("TW", "Twi"),
  TY("TY", "Tahitian"),
  UG("UG", "Uyghur"),
  UK("UK", "Ukrainian"),
  UR("UR", "Urdu"),
  UZ("UZ", "Uzbek"),
  VE("VE", "Venda"),
  VI("VI", "Vietnamese"),
  VO("VO", "Volapük"),
  WA("WA", "Walloon"),
  WO("WO", "Wolof"),
  XH("XH", "Xhosa"),
  YI("YI", "Yiddish"),
  YO("YO", "Yoruba"),
  ZA("ZA", "Zhuang"),
  ZH("ZH", "Chinese"),
  ZU("ZU", "Zulu")
}